services:
  - type: web
    name: nelsonbot
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080